apiVersion: v1
kind: Service
metadata:
  name: resource-failure-svc
  namespace: apps
  labels:
    not: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    not: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-failure
  namespace: apps
  labels:
    not: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      not: nginx
  template:
    metadata:
      labels:
        not: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 100m
            memory: 500Mi

