apiVersion: v1
kind: Service
metadata:
  labels:
    app: dax-custom-webhook
  name: dax-custom-webhook
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: dax-custom-webhook